namespace ShoppingSystem.Microservice.Domain.Common;

/// <summary>
/// Represents the base class for aggregate roots in the domain model.
/// Aggregate roots are responsible for maintaining consistency boundaries
/// and managing domain events generated by their internal state changes.
/// </summary>
public class AggregateRoot : BaseEntity
{
    // Internal collection used to store domain events raised by this aggregate.
    private readonly List<IDomainEvent> _domainEvents = new();


    /// <summary>
    /// Provides read-only access to the domain events generated by this aggregate.
    /// </summary>
    public IReadOnlyCollection<IDomainEvent> DomainEvents =>
        _domainEvents.AsReadOnly();


    /// <summary>
    /// Raises a domain event and adds it to the pending events collection.
    /// </summary>
    /// <param name="domainEvent">The domain event to add.</param>
    protected void Raise(IDomainEvent domainEvent)
    {
        _domainEvents.Add(domainEvent);
    }


    /// <summary>
    /// Removes all stored domain events from the aggregate.
    /// Usually called after events have been successfully published.
    /// </summary>
    public void ClearDomainEvents()
    {
        _domainEvents.Clear();
    }
    

    /// <summary>
    /// Adds a domain event to the aggregate event collection.
    /// </summary>
    /// <param name="domainEvent">The domain event to add.</param>
    protected void AddDomainEvent(DomainEvent domainEvent)
    {
        _domainEvents.Add(domainEvent);
    }
}